cmake_minimum_required(VERSION 3.18)

string(TOUPPER "${verboten}" VERBOTEN)
set(file "${verboten}-nightly-source.zip")
set(url "https://archive.org/download/${verboten}-nightly/${file}")
set(root "${CMAKE_CURRENT_LIST_DIR}")
set(archive "${root}/${file}")

file(DOWNLOAD "${url}" "${archive}")
file(ARCHIVE_EXTRACT INPUT "${archive}" DESTINATION "${root}")
file(RENAME "${root}/${verboten}-nightly" "${root}/3ds-nightly")
file(REMOVE "${archive}")

set(libressl "https://web.archive.org/web/20240228021547if_/https://codeload.github.com/${verboten}-emu/ext-libressl-portable/zip/refs/heads/master")
set(boost "https://web.archive.org/web/20240228005443/https://codeload.github.com/${verboten}-emu/ext-boost/zip/refs/heads/master")
set(library-headers "https://web.archive.org/web/20240228014149/https://codeload.github.com/${verboten}-emu/ext-library-headers/zip/refs/heads/main")
set(sirit "https://web.archive.org/web/20240227234446/https://codeload.github.com/${verboten2}-emu/sirit/zip/refs/heads/master")
set(discord-rpc "https://web.archive.org/web/20240227231527/https://codeload.github.com/${verboten2}-emu/discord-rpc/zip/refs/heads/master")
set(dynarmic "https://web.archive.org/web/20230309190805/https://codeload.github.com/merryhime/dynarmic/zip/refs/heads/master")

foreach(x boost libressl library-headers sirit discord-rpc dynarmic)
  set(zip "${root}/${x}.zip")
  file(DOWNLOAD "${${x}}" "${zip}")
  set(out "${CMAKE_CURRENT_LIST_DIR}/out")
  file(MAKE_DIRECTORY "${out}")
  file(ARCHIVE_EXTRACT INPUT "${zip}" DESTINATION "${out}")
  file(REMOVE "${zip}")
  file(GLOB dir LIST_DIRECTORIES YES "${out}/*")
  set(dest "${root}/3ds-nightly/externals/${x}")
  file(REMOVE_RECURSE "${dest}")
  file(RENAME "${dir}" "${dest}")
  file(REMOVE_RECURSE "${out}")
endforeach()

file(READ "${root}/fix.patch.in" patch)
string(REPLACE "@verboten@" "${verboten}" patch "${patch}")
string(REPLACE "@VERBOTEN@" "${VERBOTEN}" patch "${patch}")
file(WRITE "${root}/fix.patch" "${patch}")
